### ISSUE TITLE
Add option to store UUID

### ISSUE THREAD

**Issue by magicalyak** [nginxinc/ansible-role-nginx-controller-agent#6]
in the agent.conf, you need to set store_UUID = True for persistence to work on a container or demo environment (where the underlying instance might be swapped but you want it to report the same on the controller).  We should add a variable to set this to true.  This solves that issue.

Current my workaround is this
sudo sed -i.bak 's/store_uuid = False/store_uuid = True/' /etc/controller-agent/agent.conf

**Comment by brianehlert** [comment]
just added this as default behavior whenever nginx_controller_hostname or nginx_controller_instance_name is defined.

With the expectation that if those are not defined and thus get written to the agent.conf via the installer, the hostname might change.

Instance_name will always remain fixed and is set at installation.  
However, nginx_controller_hostname could safely change.
